spring:
  application:
    name: AcademiQ
  profiles:
    active: dev

server:
  servlet:
    context-path: /api
    encoding:
      charset: UTF-8
      enabled: true
      force: true

logging:
  level:
    root: INFO
    com.academiq: DEBUG
    org.hibernate.SQL: DEBUG
