package com.academiq.entity;

public enum AuditAction {
    CONNEXION,
    CREATION_UTILISATEUR,
    MODIFICATION_UTILISATEUR,
    SUPPRESSION_UTILISATEUR,
    CHANGEMENT_ROLE,
    DESACTIVATION_COMPTE,
    ACTIVATION_COMPTE,
    SAISIE_NOTES,
    VERROUILLAGE_EVALUATION,
    DEVERROUILLAGE_EVALUATION,
    TRAITEMENT_ALERTE
}
